### PR TITLE
fix looping issue on win animations

### PR DESCRIPTION
**Pull request by JeffTheRock**
for water and snow ninjas

*note: technically not accurate to the original, however there's already a few minor changes so i dont believe it matters

### CODE REVIEW

**Comment by Lekuruu** [comment]
You guys really like to complain about every single animation lmao :D 
This sadly comes down to personal preference again, so I‘ll think about it.

**Comment by Lekuruu** [comment]
I don‘t really know if it‘s worth to change an animation, that is only displayed for like 2 seconds. My goal here is to recreate the original, and we *have* already broken that rule a few times before…

**Comment by Lekuruu** [comment]
@JeffTheRock I found a much better approach. Try setting the `play_style` to `ping_pong`.

**Comment by JeffTheRock** [comment]
im not entirely sure what that does but it does look much better than both so im down

**Review by Lekuruu — APPROVED** [review]

**Pull request merged**
