### PR TITLE
Adjust snow & water power beams

### PR DESCRIPTION
**Pull request by Lekuruu**
This adjusts some animations for the power beams. You can see the direct comparison below.

----

Snow Before:

https://github.com/Lekuruu/snowflake/assets/84310095/2981257f-bf55-4ec2-b0f4-1aaffde8e674

Snow After:

https://github.com/Lekuruu/snowflake/assets/84310095/6d683372-5920-4440-a2cb-f8fd4ee26dc8

Water Before:

https://github.com/Lekuruu/snowflake/assets/84310095/0a9477e9-1518-4a8a-8b41-61c8625b34f3

Water After:

https://github.com/Lekuruu/snowflake/assets/84310095/1f6f7249-d96d-4557-80e7-2bec5ef3e544

### CODE REVIEW

**Comment by Lekuruu** [comment]
@jefftherock what do you think?

**Comment by renanrcp** [comment]
seems better

**Comment by JeffTheRock** [comment]
snow is still slightly too high and fire is nowhere to be found, however water is perfect.
can't wait!

**Comment by Lekuruu** [comment]
I thought fire was fine, so I left it lmao

**Comment by Lekuruu** [comment]
Give me a minute

**Comment by Lekuruu** [comment]
image
Is this okay?

**Comment by JeffTheRock** [comment]
perfect!

**Comment by Lekuruu** [comment]
The fire ninja has no issues btw. (or I am just blind, no clue lol)

**Comment by JeffTheRock** [comment]
im just blind apparently
looks good to me, can be merged

**Comment by Lekuruu** [comment]
I fixed the duration of the fire beam, since that is probably what was throwing you off

**Pull request merged**
